#!/usr/bin/env bash
# Displays 'To infinity and beyond' indefinitely but 'I am invincible!!!' when receives a SIGTERM.

while true
do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "I am invincible!!!"' SIGTERM
done
