#!/usr/bin/env bash
# Displays number 1 to 100 Fizzbuzz'ly (IYKYK).

idx=1
while [ $idx -le 100 ]
do
    if [ $((idx%3)) = 0 ] && [ $((idx%5)) = 0 ]
    then
        echo "FizzBuzz"
    elif [ $((idx%3)) = 0 ]
    then
        echo "Fizz"
    elif [ $((idx%5)) = 0 ]
    then
        echo "Buzz"
    else
        echo "$INDEX"
    fi
        (( idx+=1 ))
done
