#!/usr/bin/env bash
# Displays username, user id and home path of file  /etc/passwd.

# Open /etc/passwd file.
exec 3< /etc/passwd


while IFS= read -r line
do
    # Display fields 1, 3, 6 of the line.
    echo "$line" | cut -d':' --fields=1,3,6
done <&3

# Close file
exec 3<&-
