#!/usr/bin/env bash
# Displays 1 to 20 except in case of after 1. 4 - 'bad luck from China',
# 2. 9 'bad luck from Japan', 3. 17 'bad luck from Italy'.

idx=1
while [ $idx -le 20 ]
do
    case $idx in
        4)
	    echo $idx
	    echo "bad luck from China"
	    ;;
	9)
	    echo $idx
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo $idx
	    echo "bad luck from Italy"
	    ;;
	*)
	    echo $idx
	    ;;
    esac

    (( idx+=1 ))
done
